# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creatd_date',
            new_name='created_date',
        ),
    ]
