# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160503_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='location',
            field=models.ImageField(upload_to=b'images/', verbose_name=b'Image'),
        ),
    ]
