# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160817_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttext',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
