# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-04-17 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160817_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttext',
            name='text',
            field=models.TextField(verbose_name=b'Textblock'),
        ),
    ]
